### ISSUE TITLE
[in_tail_container_logs] pattern not matched - tried everything, not sure what I am missing

### ISSUE THREAD

**Issue by kjroger94** [fluent/fluentd-kubernetes-daemonset#434] opened 2020-04-30 13:50 UTC
Hi, 

I am using https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.9/debian-cloudwatch as reference to install this image as a sidecar in a kubernetes pod. 

Added these additional ENVs
```
ENV FLUENTD_SYSTEMD_CONF disable
ENV FLUENTD_PROMETHEUS_CONF disable
ENV FLUENT_ELASTICSEARCH_SED_DISABLE "true"
```
along with Log group name and region for AWS Cloudwatch

_fluent.conf_
```
@include "#{ENV['FLUENTD_SYSTEMD_CONF'] || 'systemd'}.conf"
@include "#{ENV['FLUENTD_PROMETHEUS_CONF'] || 'prometheus'}.conf"
@include kubernetes.conf
@include conf.d/*.conf

<match **>
  @type cloudwatch_logs
  @id out_cloudwatch_logs
  log_group_name "#{ENV['LOG_GROUP_NAME']}"
  auto_create_stream true
  use_tag_as_stream true
  retention_in_days "7"
  json_handler yajl # To avoid UndefinedConversionError
  log_rejected_request "true" # Log rejected request for missing parts
</match>

```

_kubernetes.conf_

<label @FLUENT_LOG>
  <match fluent.**>
    @type null
  </match>
</label>

```
<source>
  @type tail
  @id in_tail_container_logs
  path /root/.pm2/logs/*.log
  pos_file /root/.pm2/sys.log.pos
  tag kubernetes.*
  exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
  read_from_head true
  <parse>
    @type json
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </parse>
</source>
```
Fluentd is tailing the logs but no matter what config i try - 
```
2020-04-30 13:08:40 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "\e[0mGET / \e[32m200 \e[0m45.213 ms - 170\e[0m"
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "{"
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "  \"level\": \"info\","
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "  \"message\": \"hello from slash\","
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "  \"timestamp\": \"2020-04-30T13:08:41.075Z\""
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "}"
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "logloglog"
2020-04-30 13:08:41 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "\e[0mGET / \e[32m200 \e[0m10.925 ms - 170\e[0m"

```

What am I missing? If you look closely it has plain text, it has a JSON i have tried everything.

**Comment by iamparamvs** [comment] 2020-06-25 08:17
Facing a similar issue.

Anyone has any leads?

**Comment by vimalcloud** [comment] 2020-08-04 08:27
facing same  issue but with  hosted k8s

**Comment by jkawamoto** [comment] 2020-08-05 19:33
Looks like your container doesn't write logs in proper JSON format. Each JSON object should be written in one line unless you configure [multiline parser plugin](https://docs.fluentd.org/parser/multiline).

**Comment by dyipon** [comment] 2020-09-23 07:48
same here with a k3s cluster
`2020-09-23 07:48:03 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-09-23T09:47:45.307936186+02:00 stdout F 2020-09-23 07:47:45 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: \"2020-09-23T09:47:34.334985467+02:00 stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\""`

**Comment by dyipon** [comment] 2020-09-23 11:38
`  "exclude_path ["/var/log/containers/fluent*"]" `
in kubernetes.conf solved it

**Comment by Sieabah** [comment] 2020-12-17 03:03
While I did have an issue with fluentd logs perpetually causing the pods themselves to die (from ingesting their own logs) it still doesn't work.

My outputs are single line JSON objects but fluentd still fails to parse them as json.

Source definition
```
<source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
```

The logs as-is directly from the container

![image](https://user-images.githubusercontent.com/650333/102438407-3f30ec00-3fea-11eb-912a-76bd1c635ef8.png)

This is how fluentd picks them up. 

![image](https://user-images.githubusercontent.com/650333/102438456-51ab2580-3fea-11eb-8ab8-5690651a4106.png)

Is the date prefix injected by something? 

Found my way here trying to get fluentd working with elasticsearch and so far not a single log from anything other than the kubelet is able to make it to the elasticsearch cluster.

![image](https://user-images.githubusercontent.com/650333/102438559-86b77800-3fea-11eb-8051-0d5029f47e94.png)

**Comment by Sieabah** [comment] 2020-12-17 04:06
So the problem comes down to the some kubernetes logging format that is documented poorly in code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/logs/logs.go#L125-L169)

So all of the problems besides OP's multiline issue is down to kubernetes writing logs into the CRI log format and fluentd being incapable of parsing it without using regex. Actually just tested this regex `/^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<message>.*)$/`.

I stumbled upon this [GCP fluentd configuration for stackdriver](https://fossies.org/linux/kubernetes/cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml) which gave this regexp `/^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/` if the previous doesn't end up working.

So I have logs being picked up, but they are not parsed the json payload is stored in `message` from the first regex.

**Comment by agup006** [comment] 2020-12-17 04:33
@Siebah This is the CRI parser we ship with Fluent Bit:

```
# CRI Parser
[PARSER]
    # http://rubular.com/r/tjUt3Awgg4
    Name cri
    Format regex
    Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```

I believe the same one as the GCP fluentd configuration for stackdriver. I can potentially update the Fluentd docs as a heads up though from your last message are you still not able to parse them in the intended JSON format?

https://docs.fluentbit.io/manual/installation/kubernetes#container-runtime-interface-cri-parser

**Comment by Sieabah** [comment] 2020-12-17 04:45
I've struggled a lot to get it to work and I have no idea if it's even the proper way. @agup006 

I stumbled upon this semi-working config on a separate issue [here](https://github.com/fluent/fluentd/issues/2073#issuecomment-409469227).

I'll paste a copy of the working conf here, but for reference [this is my post in the other issue about it](https://github.com/fluent/fluentd/issues/2073#issuecomment-747201456)
```
<source>
  @type tail
  @id in_tail_container_logs
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  exclude_path ["/var/log/containers/fluent*"]
  read_from_head true
  <parse>
    @type regexp
    expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
  </parse>
</source>
<filter kubernetes.**>
  @type kubernetes_metadata
  @id filter_kube_metadata
</filter>

<filter kubernetes.var.log.containers.**>
  @type parser
  <parse>
    @type json
    json_parser json
  </parse>
  replace_invalid_sequence true
  emit_invalid_record_to_error false
  key_name log
  reserve_data true
</filter>
```

**Comment by repeatedly** [comment] 2020-12-18 01:41
We are now working on parser_cri for containerd/cri-o runtime: https://github.com/fluent/fluent-plugin-parser-cri/blob/main/lib/fluent/plugin/parser_cri.rb
We will release this parser soon and k8s-deamonset will support this parser.

**Comment by bangonkali** [comment] 2020-12-31 01:47
Hi @dyipon, regarding your comment on https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-697307365, how do you exactly install/save this configuration on k3s?

I am currently using this instruction https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes but for some reason i have the same behavior as yours. I am also on K3s..

```
...
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.005973968Z stdout F \\\""
2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.007853069Z stdout P 2020-12-31 01:44:29 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: \"2020-12-31T01:44:20.324108311Z stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\^C\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
...
```

I searched for `kubernetes.conf` and i see the following files but I'm not sure which one is relevant here.

```
/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/777/fs/fluentd/etc/kubernetes.conf
/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/660/fs/fluentd/etc/kubernetes.conf
/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/709/fs/fluentd/etc/kubernetes.conf
/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/e54a72bed5ca0cc4fbcab1556d01ba31957e27208f1b8d46cee0693d08e0d636/rootfs/fluentd/etc/kubernetes.conf
```

**Comment by RainFlying** [comment] 2021-04-20 18:09
> Hi @dyipon, regarding your comment on [#434 (comment)](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-697307365), how do you exactly install/save this configuration on k3s?
> 
> I am currently using this instruction https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes but for some reason i have the same behavior as yours. I am also on K3s..
> 
> ```
> ...
> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
> 2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.005973968Z stdout F \\\""
> 2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.007853069Z stdout P 2020-12-31 01:44:29 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: \"2020-12-31T01:44:20.324108311Z stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\^C\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
> ...
> ```
> 
> I searched for `kubernetes.conf` and i see the following files but I'm not sure which one is relevant here.
> 
> ```
> /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/777/fs/fluentd/etc/kubernetes.conf
> /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/660/fs/fluentd/etc/kubernetes.conf
> /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/709/fs/fluentd/etc/kubernetes.conf
> /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/e54a72bed5ca0cc4fbcab1556d01ba31957e27208f1b8d46cee0693d08e0d636/rootfs/fluentd/etc/kubernetes.conf
> ```
> 
> ### Update
> Okay, after further fumbling around the internets. I seemed to have figured out how to go over this. Still based on the context that I'm following this [Guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes).
> 
> I edited the `fluentd.yaml` according to this.
> 
> ```yaml
> # fluentd.yaml
> ...
> containers:
> - name: fluentd
>   image: fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-elasticsearch7-1.1
>   env:
>     - name:  FLUENT_ELASTICSEARCH_HOST
>       value: "10.0.2.15"
>     - name:  FLUENT_ELASTICSEARCH_PORT
>       value: "9200"
>     - name: FLUENT_ELASTICSEARCH_SCHEME
>       value: "http"
>     - name: FLUENTD_SYSTEMD_CONF
>       value: disable
>     - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
>       value: /var/log/containers/fluent*
>     - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
>       value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
>   resources:
>     limits:
>       memory: 1024Mi
>     requests:
>       cpu: 100m
>       memory: 200Mi
> ...
> ```
> 
> * `FLUENT_CONTAINER_TAIL_EXCLUDE_PATH` prevents the circular log.
> * `FLUENT_CONTAINER_TAIL_PARSER_TYPE` ensures it can read the logs.

Followed the same guide and used the same config as in your comment. Still can't get logs into Elasticsearch. Acutally there are logs in Elasticsearch, all of them are Prometheus out of bound error log as the following:
```
kubernetes.container_name:prometheus stream:stderr logtag:F log:level=warn ts=2021-04-20T18:08:45.206Z caller=scrape.go:1378 component="scrape manager" scrape_pool=monitoring/kubelet/2 target=https://172.19.0.3:10250/metrics/probes msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=4 docker.container_id:a92878f44a11e94f3081aa100c6defc3bf69711daffa9804597b8893844cd556 kubernetes.namespace_name:monitoring kubernetes.pod_name:prometheus-k8s-1 kubernetes.container_image:quay.io/prometheus/prometheus:v2.24.0 kubernetes.container_image_id:quay.io/prometheus/prometheus@sha256:943c7c57115a449353e0158dcba4eaab2e56de07b7d552b5145cb6c0d1cbab19
```

**Comment by dyipon** [comment] 2021-04-21 06:30
@RainFlying maybe it's timezone issue. If I remember well, i just had to sync the timezones between fluentd and ES.

**Comment by sysadmiral** [comment] 2021-04-29 13:26
> We are now working on parser_cri for containerd/cri-o runtime: https://github.com/fluent/fluent-plugin-parser-cri/blob/main/lib/fluent/plugin/parser_cri.rb
> We will release this parser soon and k8s-deamonset will support this parser.

Did this parser get included in any of the releases since then?

I am running `"imageID": "docker.io/fluent/fluentd-kubernetes-daemonset@sha256:7fe512f670eda2df363c44b6c8b4a505ca35f238032a6ddf75c98b33e56b8088"` which was published 1 day ago but still encountering this issue. We seem to have a corresponding increase in cluster CPU usage as well.

**Comment by sysadmiral** [comment] 2021-05-04 09:20
> > We are now working on parser_cri for containerd/cri-o runtime: https://github.com/fluent/fluent-plugin-parser-cri/blob/main/lib/fluent/plugin/parser_cri.rb
> > We will release this parser soon and k8s-deamonset will support this parser.
> 
> Did this parser get included in any of the releases since then?
> 
> I am running `"imageID": "docker.io/fluent/fluentd-kubernetes-daemonset@sha256:7fe512f670eda2df363c44b6c8b4a505ca35f238032a6ddf75c98b33e56b8088"` which was published 1 day ago but still encountering this issue. We seem to have a corresponding increase in cluster CPU usage as well.

I can confirm the parser is in recent versions of the image but you have to override the `tail_container_parse.conf` with the following (using a configmap and volumemount):

```
<parse>
  @type cri
</parse>
```

**Comment by cosmo0920** [comment] 2021-05-12 00:39
Solution is found here: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-831801690
Closing.

**Closed by cosmo0920** 2021-05-12 00:39 UTC

**Comment by alexcpn** [comment] 2021-06-25 06:36
> > > We are now working on parser_cri for containerd/cri-o runtime: https://github.com/fluent/fluent-plugin-parser-cri/blob/main/lib/fluent/plugin/parser_cri.rb
> > > We will release this parser soon and k8s-deamonset will support this parser.
> > 
> > 
> > Did this parser get included in any of the releases since then?
> > I am running `"imageID": "docker.io/fluent/fluentd-kubernetes-daemonset@sha256:7fe512f670eda2df363c44b6c8b4a505ca35f238032a6ddf75c98b33e56b8088"` which was published 1 day ago but still encountering this issue. We seem to have a corresponding increase in cluster CPU usage as well.
> 
> I can confirm the parser is in recent versions of the image but you have to override the `tail_container_parse.conf` with the following (using a configmap and volumemount):
> 
> ```
> <parse>
>   @type cri
> </parse>
> ```

In v1.12 this works - 
(the earlier setting https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-752813739 is not longer present  from v1.12 https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.12/debian-elasticsearch6)

**Comment by bognerf** [comment] 2021-07-26 14:10
I would like to confirm that it works when using a v1.12 image. From v1.13 on the  `pattern not matched` error returned.

**Comment by juicycool92** [comment] 2021-08-05 08:48
> ```yaml
> - name: FLUENTD_SYSTEMD_CONF
>       value: disable
>     - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
>       value: /var/log/containers/fluent*
>     - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
>       value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
> ```

geez,
I spent three days to resolve several issues, than finally found env values from your comment!
Thankyou so much!

**Comment by ziyanakthar** [comment] 2021-09-09 17:28
Hello Team

I recently upgraded to k8s v1.20 using CRI-O and I managed to fix the issue to the get kubernetes logs pushed to elasticsearch via fluentd v1.14.0 but the weird issue is, fluentd adds a new empty line/new line character in the logs which appends in the stdout as well. Can you please advise how to avoid this to not to add a new line.

**Comment by ziyanakthar** [comment] 2021-09-09 17:29
For example

**Comment by paulliss** [comment] 2022-01-14 12:36
works for me:

`        env:`
`          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE`
           ` value: cri`

**Comment by shadycuz** [comment] 2022-12-26 13:42
Also having the pattern match error regardless if I use the regex or cri value. for `FLUENT_CONTAINER_TAIL_PARSER_TYPE`

**Comment by alex-orange** [comment] 2023-01-03 19:30
For me I needed to change the time format from:
`time_format '%Y-%m-%dT%H:%M:%S.%NZ'`
to
`time_format '%Y-%m-%dT%H:%M:%S.%N%:z'`

I'm using the fluentd helm chart, so I added this section:

```
fileConfigs:
  01_sources.conf: |-
    ## logs from podman
    <source>
      @type tail
      @id in_tail_container_logs
      @label @KUBERNETES
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_type string
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
          keep_time_key false
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
          time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
          keep_time_key false
        </pattern>
      </parse>
      emit_unmatched_lines true
    </source>
```

Sorry, I didn't get enough time to read about your setup, but I hope this is helpful for others. The root cause of this seems to be that the default expects a 'Z' for the timezone (UTC if I understand correct), and containterd (or whatever is creating your logs) is logging in your local timezone.

**Comment by dinglimingzh** [comment] 2023-09-02 04:10
2023-09-02 04:08:24 +0000 [warn]: #0 [in_tail_container_logs] invalid line found file="/var/log/containers/kube-apiserver-k8s-master1_kube-system_kube-apiserver-fab2e15bb0f7356fc4ebbff55f19acc2f77c80ea317aef378dfd734c91328b95.log" line="2023-09-02T12:08:24.033002417+08:00 stderr F Trace[1690218134]: [5.048821459s] [5.048821459s] END" error="invalid time format: value = 2023-09-02T12:08:24.033002417+08:00, error_class = ArgumentError, error = string doesn't match"

**Comment by dinglimingzh** [comment] 2023-09-03 00:38
What kind of question is that?

**Comment by fenixpapu** [comment] 2023-11-26 18:18
> > Hi @dyipon, regarding your comment on [#434 (comment)](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-697307365), how do you exactly install/save this configuration on k3s?
> > I am currently using this instruction https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes but for some reason i have the same behavior as yours. I am also on K3s..
> > ```
> > ...
> > \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"
> > 2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.005973968Z stdout F \\\""
> > 2020-12-31 01:44:44 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: "2020-12-31T01:44:29.007853069Z stdout P 2020-12-31 01:44:29 +0000 [warn]: #0 [in_tail_container_logs] pattern not matched: \"2020-12-31T01:44:20.324108311Z stdout F \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\^C\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I searched for `kubernetes.conf` and i see the following files but I'm not sure which one is relevant here.
> > ```
> > /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/777/fs/fluentd/etc/kubernetes.conf
> > /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/660/fs/fluentd/etc/kubernetes.conf
> > /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/709/fs/fluentd/etc/kubernetes.conf
> > /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/e54a72bed5ca0cc4fbcab1556d01ba31957e27208f1b8d46cee0693d08e0d636/rootfs/fluentd/etc/kubernetes.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Update
> > Okay, after further fumbling around the internets. I seemed to have figured out how to go over this. Still based on the context that I'm following this [Guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes).
> > I edited the `fluentd.yaml` according to this.
> > ```yaml
> > # fluentd.yaml
> > ...
> > containers:
> > - name: fluentd
> >   image: fluent/fluentd-kubernetes-daemonset:v1.11.5-debian-elasticsearch7-1.1
> >   env:
> >     - name:  FLUENT_ELASTICSEARCH_HOST
> >       value: "10.0.2.15"
> >     - name:  FLUENT_ELASTICSEARCH_PORT
> >       value: "9200"
> >     - name: FLUENT_ELASTICSEARCH_SCHEME
> >       value: "http"
> >     - name: FLUENTD_SYSTEMD_CONF
> >       value: disable
> >     - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
> >       value: /var/log/containers/fluent*
> >     - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
> >       value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
> >   resources:
> >     limits:
> >       memory: 1024Mi
> >     requests:
> >       cpu: 100m
> >       memory: 200Mi
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * `FLUENT_CONTAINER_TAIL_EXCLUDE_PATH` prevents the circular log.
> > * `FLUENT_CONTAINER_TAIL_PARSER_TYPE` ensures it can read the logs.
> 
> Followed the same guide and used the same config as in your comment. Still can't get logs into Elasticsearch. Acutally there are logs in Elasticsearch, all of them are Prometheus out of bound error log as the following:
> 
> ```
> kubernetes.container_name:prometheus stream:stderr logtag:F log:level=warn ts=2021-04-20T18:08:45.206Z caller=scrape.go:1378 component="scrape manager" scrape_pool=monitoring/kubelet/2 target=https://172.19.0.3:10250/metrics/probes msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=4 docker.container_id:a92878f44a11e94f3081aa100c6defc3bf69711daffa9804597b8893844cd556 kubernetes.namespace_name:monitoring kubernetes.pod_name:prometheus-k8s-1 kubernetes.container_image:quay.io/prometheus/prometheus:v2.24.0 kubernetes.container_image_id:quay.io/prometheus/prometheus@sha256:943c7c57115a449353e0158dcba4eaab2e56de07b7d552b5145cb6c0d1cbab19
> ```

For someone like me, I'm using: `fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch` and this config does not work.
But the same config in source work for me:
```
    <source>
      @type tail
      ....
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      </parse>
    </source>
    ```

**Comment by berezinsn** [comment] 2025-03-10 10:23
> For me I needed to change the time format from: `time_format '%Y-%m-%dT%H:%M:%S.%NZ'` to `time_format '%Y-%m-%dT%H:%M:%S.%N%:z'`
> 
> I'm using the fluentd helm chart, so I added this section:
> 
> ```
> fileConfigs:
>   01_sources.conf: |-
>     ## logs from podman
>     <source>
>       @type tail
>       @id in_tail_container_logs
>       @label @KUBERNETES
>       path /var/log/containers/*.log
>       pos_file /var/log/fluentd-containers.log.pos
>       tag kubernetes.*
>       read_from_head true
>       <parse>
>         @type multi_format
>         <pattern>
>           format json
>           time_key time
>           time_type string
>           time_format "%Y-%m-%dT%H:%M:%S.%NZ"
>           keep_time_key false
>         </pattern>
>         <pattern>
>           format regexp
>           expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
>           time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
>           keep_time_key false
>         </pattern>
>       </parse>
>       emit_unmatched_lines true
>     </source>
> ```
> 
> Sorry, I didn't get enough time to read about your setup, but I hope this is helpful for others. The root cause of this seems to be that the default expects a 'Z' for the timezone (UTC if I understand correct), and containterd (or whatever is creating your logs) is logging in your local timezone.

Thank you! All the logs got broken on CRI without the time format you provided! God bless :)
