### ISSUE TITLE
Docker image does not build due to lack of /bin/sh

### ISSUE THREAD

**Issue by boeboe** [fluent/fluentd-kubernetes-daemonset#2] opened 2017-02-02 10:54 UTC
Building the docker image results in errors:

	# docker build .
	Sending build context to Docker daemon 11.26 kB
	Step 1/11 : FROM fluent/fluentd:v0.12-onbuild
	# Executing 2 build triggers...
	Step 1/1 : COPY fluent.conf /fluentd/etc/
	 ---> Using cache
	Step 1/1 : COPY plugins /fluentd/plugins/
	 ---> Using cache
	 ---> 14ec4026e25b
	Step 2/11 : MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
	 ---> Running in 03b78de3d801
	 ---> fef1e854802f
	Removing intermediate container 03b78de3d801
	Step 3/11 : USER root
	 ---> Running in 6e106da769a9
	 ---> d5bbf8093c4a
	Removing intermediate container 6e106da769a9
	Step 4/11 : WORKDIR /home/fluent
	 ---> 995a21b0438a
	Removing intermediate container 244a814f84bf
	Step 5/11 : ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
	 ---> Running in dee529338d96
	 ---> 584670a50962
	Removing intermediate container dee529338d96
	Step 6/11 : RUN apk --no-cache --update add                             build-base                             ruby-dev &&     echo 'gem: --no-document' >> /etc/gemrc &&     gem install fluent-plugin-secure-forward &&     gem install fluent-plugin-record-reformer &&     gem install fluent-plugin-elasticsearch &&     gem install fluent-plugin-kubernetes_metadata_filter &&     apk del build-base ruby-dev &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem
	 ---> Running in eb277b33fbd2
	container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
	oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

It fails on the following line of the Dockerfile due to lack of /bin/sh in base image:

	RUN apk --no-cache --update add \
								build-base \
								ruby-dev && \
		echo 'gem: --no-document' >> /etc/gemrc && \
		gem install fluent-plugin-secure-forward && \
		gem install fluent-plugin-record-reformer && \
		gem install fluent-plugin-elasticsearch && \
		gem install fluent-plugin-kubernetes_metadata_filter && \
		apk del build-base ruby-dev && \
		rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem

**Comment by edsiper** [comment] 2017-02-08 18:01
Thanks for the report.

With the latest changes I could not reproduce the problem, it builds fine.

```
$ docker build .
Sending build context to Docker daemon 14.85 kB
Step 1 : FROM fluent/fluentd:v0.12-onbuild
v0.12-onbuild: Pulling from fluent/fluentd
b7f33cc0b48e: Already exists 
ba147756ff28: Pull complete 
d8453829fc8a: Pull complete 
0460677fb993: Pull complete 
9e1f4d765f08: Pull complete 
efe824b95d21: Pull complete 
8670a3fd7495: Pull complete 
02626862439e: Pull complete 
Digest: sha256:07c5d8d2b6575c761172662f976265335e746c2bb0e7da078856b80ca5705355
Status: Downloaded newer image for fluent/fluentd:v0.12-onbuild
# Executing 2 build triggers...
Step 1 : COPY fluent.conf /fluentd/etc/
Step 1 : COPY plugins /fluentd/plugins/
 ---> a03b87536809
Removing intermediate container 11055ecfe030
Removing intermediate container 91c4e4d15cc6
Step 2 : MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
 ---> Running in 996327df775d
 ---> 5249003732f9
Removing intermediate container 996327df775d
Step 3 : USER root
 ---> Running in 0f49de0fb2be
 ---> 07e203bd3505
Removing intermediate container 0f49de0fb2be
Step 4 : WORKDIR /home/fluent
 ---> Running in 9ff33352b5c9
 ---> b4328f128cc8
Removing intermediate container 9ff33352b5c9
Step 5 : ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
 ---> Running in 2eb38e68a463
 ---> 2427141cd450
Removing intermediate container 2eb38e68a463
Step 6 : RUN apk --no-cache --update add                             build-base                             ruby-dev &&     echo 'gem: --no-document' >> /etc/gemrc &&     gem install fluent-plugin-secure-forward &&     gem install fluent-plugin-record-reformer &&     gem install fluent-plugin-elasticsearch &&     gem install fluent-plugin-kubernetes_metadata_filter &&     apk del build-base ruby-dev &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem
 ---> Running in 0af7f24caf4d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/21) Installing binutils-libs (2.26-r0)
(2/21) Installing binutils (2.26-r0)
(3/21) Installing isl (0.14.1-r0)
(4/21) Installing libgomp (5.3.0-r0)
(5/21) Installing libatomic (5.3.0-r0)
(6/21) Installing libgcc (5.3.0-r0)
(7/21) Installing pkgconf (0.9.12-r0)
(8/21) Installing pkgconfig (0.25-r1)
(9/21) Installing mpfr3 (3.1.2-r0)
(10/21) Installing mpc1 (1.0.3-r0)
(11/21) Installing libstdc++ (5.3.0-r0)
(12/21) Installing gcc (5.3.0-r0)
(13/21) Installing make (4.1-r1)
(14/21) Installing musl-dev (1.1.14-r14)
(15/21) Installing libc-dev (0.7-r0)
(16/21) Installing fortify-headers (0.8-r0)
(17/21) Installing g++ (5.3.0-r0)
(18/21) Installing build-base (0.4-r1)
(19/21) Installing libgmpxx (6.1.0-r0)
(20/21) Installing gmp-dev (6.1.0-r0)
(21/21) Installing ruby-dev (2.3.1-r0)
Executing busybox-1.24.2-r12.trigger
OK: 185 MiB in 44 packages
Successfully installed resolve-hostname-0.1.0
Successfully installed proxifier-1.0.3
Successfully installed fluent-plugin-secure-forward-0.4.3
3 gems installed
Successfully installed fluent-plugin-record-reformer-0.8.3
1 gem installed
Successfully installed excon-0.55.0
Successfully installed multi_json-1.12.1
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.11.0
Successfully installed elasticsearch-transport-1.0.18
Successfully installed elasticsearch-api-1.0.18
Successfully installed elasticsearch-1.0.18
Successfully installed fluent-plugin-elasticsearch-1.9.2
8 gems installed
Successfully installed lru_redux-1.1.0
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.2
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20161129
Successfully installed http-cookie-1.0.3
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed netrc-0.11.0
Successfully installed rest-client-2.0.0
Successfully installed i18n-0.8.0
Successfully installed concurrent-ruby-1.0.4
Successfully installed activesupport-5.0.1
Successfully installed recursive-open-struct-1.0.0
Successfully installed http-form_data-1.0.1
Successfully installed public_suffix-2.0.5
Successfully installed addressable-2.5.0
Successfully installed http-0.9.8
Successfully installed kubeclient-1.1.4
Successfully installed fluent-plugin-kubernetes_metadata_filter-0.26.2
19 gems installed
(1/21) Purging build-base (0.4-r1)
(2/21) Purging make (4.1-r1)
(3/21) Purging fortify-headers (0.8-r0)
(4/21) Purging g++ (5.3.0-r0)
(5/21) Purging gcc (5.3.0-r0)
(6/21) Purging binutils (2.26-r0)
(7/21) Purging isl (0.14.1-r0)
(8/21) Purging libatomic (5.3.0-r0)
(9/21) Purging libc-dev (0.7-r0)
(10/21) Purging musl-dev (1.1.14-r14)
(11/21) Purging ruby-dev (2.3.1-r0)
(12/21) Purging gmp-dev (6.1.0-r0)
(13/21) Purging libgmpxx (6.1.0-r0)
(14/21) Purging pkgconfig (0.25-r1)
(15/21) Purging pkgconf (0.9.12-r0)
(16/21) Purging binutils-libs (2.26-r0)
(17/21) Purging libgomp (5.3.0-r0)
(18/21) Purging libstdc++ (5.3.0-r0)
(19/21) Purging libgcc (5.3.0-r0)
(20/21) Purging mpc1 (1.0.3-r0)
(21/21) Purging mpfr3 (3.1.2-r0)
Executing busybox-1.24.2-r12.trigger
OK: 28 MiB in 23 packages
 ---> 1fe92734ae7e
Removing intermediate container 0af7f24caf4d
Step 7 : COPY ./conf/fluent.conf /fluentd/etc/
 ---> 721bddd98ff8
Removing intermediate container e58d68aaaaff
Step 8 : COPY ./conf/kubernetes.conf /fluentd/etc/
 ---> 2da2ac0c740b
Removing intermediate container 48bb1066f120
Step 9 : ENV FLUENTD_OPT ""
 ---> Running in 5c6d657265b1
 ---> 9b6892bbf48d
Removing intermediate container 5c6d657265b1
Step 10 : ENV FLUENTD_CONF "fluent.conf"
 ---> Running in 7e98b7ba14e8
 ---> 34327445bef2
Removing intermediate container 7e98b7ba14e8
Step 11 : CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
 ---> Running in 474db153c4f0
 ---> eded839493d7
Removing intermediate container 474db153c4f0
Successfully built eded839493d7
```

Closing the Issue. If you face a similar problem, please re-open it.

**Closed by edsiper** 2017-02-08 18:01 UTC

**Comment by boeboe** [comment] 2017-02-09 14:52
Hi @edsiper 

On my system (MacOSX El Capitan) it does not work. I tried from a fresh git clone. Full logs to reproduce hereby:

	➜  /tmp git clone https://github.com/fluent/fluentd-kubernetes-daemonset.git
	Cloning into 'fluentd-kubernetes-daemonset'...
	remote: Counting objects: 45, done.
	remote: Compressing objects: 100% (3/3), done.
	remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 42
	Unpacking objects: 100% (45/45), done.
	➜  /tmp cd fluentd-kubernetes-daemonset
	➜  fluentd-kubernetes-daemonset git:(master) ls
	README.md                             fluentd-daemonset-elasticsearch.yaml
	docker-image/
	➜  fluentd-kubernetes-daemonset git:(master) cd docker-image
	➜  docker-image git:(master) ls
	Dockerfile   conf/        fluent.conf  plugins/
	➜  docker-image git:(master) docker build . -t fluent/fluentd-kubernetes-ds:test
	Sending build context to Docker daemon 11.26 kB
	Step 1/11 : FROM fluent/fluentd:v0.12-onbuild
	# Executing 2 build triggers...
	Step 1/1 : COPY fluent.conf /fluentd/etc/
	Step 1/1 : COPY plugins /fluentd/plugins/
	 ---> ae48b2ee1a1b
	Removing intermediate container b9220899cc89
	Removing intermediate container 52b9fba35323
	Step 2/11 : MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
	 ---> Running in 620327fa32d1
	 ---> dfca9aaa9aa2
	Removing intermediate container 620327fa32d1
	Step 3/11 : USER root
	 ---> Running in 7e65df6e3e3c
	 ---> fcb411736178
	Removing intermediate container 7e65df6e3e3c
	Step 4/11 : WORKDIR /home/fluent
	 ---> d62974a0190b
	Removing intermediate container 57ccfa144994
	Step 5/11 : ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
	 ---> Running in 69a2dae5e22f
	 ---> 836744e950c2
	Removing intermediate container 69a2dae5e22f
	Step 6/11 : RUN apk --no-cache --update add                             build-base                             ruby-dev &&     echo 'gem: --no-document' >> /etc/gemrc &&     gem install fluent-plugin-secure-forward &&     gem install fluent-plugin-record-reformer &&     gem install fluent-plugin-elasticsearch &&     gem install fluent-plugin-kubernetes_metadata_filter &&     apk del build-base ruby-dev &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem
	 ---> Running in 12d9a86abc18
	container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
	oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
	➜  docker-image git:(master) docker build . -t fluent/fluentd-kubernetes-ds:test --pull
	Sending build context to Docker daemon 11.26 kB
	Step 1/11 : FROM fluent/fluentd:v0.12-onbuild
	v0.12-onbuild: Pulling from fluent/fluentd
	b7f33cc0b48e: Already exists
	ba147756ff28: Pull complete
	d8453829fc8a: Pull complete
	0460677fb993: Pull complete
	9e1f4d765f08: Pull complete
	efe824b95d21: Pull complete
	8670a3fd7495: Pull complete
	02626862439e: Pull complete
	Digest: sha256:07c5d8d2b6575c761172662f976265335e746c2bb0e7da078856b80ca5705355
	Status: Downloaded newer image for fluent/fluentd:v0.12-onbuild
	# Executing 2 build triggers...
	Step 1/1 : COPY fluent.conf /fluentd/etc/
	Step 1/1 : COPY plugins /fluentd/plugins/
	 ---> 5217bef325e5
	Removing intermediate container 31e7d897663c
	Removing intermediate container f8bb5c0d0da1
	Step 2/11 : MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
	 ---> Running in b99edb3702b5
	 ---> 3707607943b1
	Removing intermediate container b99edb3702b5
	Step 3/11 : USER root
	 ---> Running in d8403fe53339
	 ---> cb87efaf110b
	Removing intermediate container d8403fe53339
	Step 4/11 : WORKDIR /home/fluent
	 ---> 3d19c3f12f03
	Removing intermediate container b6c8748ae191
	Step 5/11 : ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
	 ---> Running in cc620cf15d8a
	 ---> 696580669c54
	Removing intermediate container cc620cf15d8a
	Step 6/11 : RUN apk --no-cache --update add                             build-base                             ruby-dev &&     echo 'gem: --no-document' >> /etc/gemrc &&     gem install fluent-plugin-secure-forward &&     gem install fluent-plugin-record-reformer &&     gem install fluent-plugin-elasticsearch &&     gem install fluent-plugin-kubernetes_metadata_filter &&     apk del build-base ruby-dev &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /usr/lib/ruby/gems/*/cache/*.gem
	 ---> Running in d4b1622d31af
	container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
	oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

It seems to me there is really something wrong with the base image (not containing /bin/sh). Is it possible you are still using some cached version that does not have this problem? Could you try with a fresh pull from the base image (adding the --pull argument as shown in the last command above)?

Best regards and really thanks for your support.
Bart
