### ISSUE TITLE
"v1-debian-gcs" tag is broken

### ISSUE THREAD

**Issue by kapec94** [fluent/fluentd-kubernetes-daemonset#1339] opened 2022-02-15 08:25 UTC
Hi,
after the latest update of `fluent/fluentd-kubernetes-daemonset:v1-debian-gcs`, I am no longer able to start the daemonset.

Pods fail with the following message:

    /usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluentd (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/local/bundle/bin/fluentd:23:in `<main>'

To reproduce, execute:

    docker run --rm fluent/fluentd-kubernetes-daemonset:v1-debian-gcs

This is probably caused by #1335 . Older image pointing to fluentd 1.4.3 works fine:

    docker run --rm fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-gcs-1.0

**Comment by ashie** [comment] 2022-02-15 08:27
Duplicate of #1336

**Closed by ashie** 2022-02-15 08:27 UTC
