### ISSUE TITLE
Unable to pull v1.12.4-debian-papertrail-1.1

### ISSUE THREAD

**Issue by Josh-Klassen-Dejero** [fluent/fluentd-kubernetes-daemonset#572] opened 2021-06-22 21:42 UTC
When trying to pull v1.12 I get the following:

``docker pull fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-papertrail-1.1``
``Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-papertrail-1.1 not found: manifest unknown: manifest unknown``

``docker pull fluent/fluentd-kubernetes-daemonset:v1.12-debian-papertrail-1``
``Error response from daemon: manifest for fluent/fluentd-kubernetes-daemonset:v1.12-debian-papertrail-1 not found: manifest unknown: manifest unknown``

Seems to be the same as #567 and #569

**Comment by kenhys** [comment] 2021-06-23 04:33
At least, the root cause is not as same as #569, it seems that the images are not pushed at all.

**Comment by cosmo0920** [comment] 2021-06-23 05:00
Papertrail image build rules are dropped due to 25 build rules limits on DockerHub.

**Comment by kenhys** [comment] 2021-07-06 03:26
It was caused by limitation, I'll close it.
Please buiild papertail image by yourself.

**Closed by kenhys** 2021-07-06 03:26 UTC
